# Dataset Creation

## Table of Contents
* [Requirements](#requirements)
* [Data Collection](#data-collection)
    * [Weather Data](#weather-data)
    * [Day-Ahead Price Data](#day-ahead-price-data)
    * [Production Data](#production-data)
    * [Cross-Border Electricity Trading Data](#cross-border-electricity-trading-data)
* [Data Concatenation](#data-concatenation)
* [Data Dictionary](#data-dictionary)

----

## Requirements

In [1]:
import sys
from pathlib import Path
import requests
from joblib import dump
from functools import reduce

import pandas as pd

from sklearn.preprocessing import StandardScaler

project_root = Path().resolve().parents[0]
sys.path.append(str(project_root))
from src.data_setup import save_splits

pd.set_option('display.max_rows', 100) 
pd.set_option('display.max_columns', 100)

/Users/benleidig/Downloads/public_repos/de_lu_epf/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

----

## Data Collection

### Weather Data

In [2]:
coordinates = [
    (52.5200, 13.4050),  # Berlin
    (53.5488, 9.9872),   # Hamburg
    (48.1351, 11.5820),  # Munich
    (50.9375, 6.9603)    # Cologne
]
weather_variables = [
    'precipitation',
    'cloud_cover',
    'sunshine',
    'temperature',
    'relative_humidity'
]

In [ ]:
%%time

url = 'https://api.brightsky.dev/weather'
parameters = {
    'date':'2018-12-31T12:00:00Z',
    'last_date':'2025-01-01T00:00:00Z'
}
concat_list = []
for lat, lon in coordinates:
    parameters['lat'] = lat
    parameters['lon'] = lon
    data = requests.get(url, parameters).json()
    temp = pd.DataFrame(data['weather'])[['timestamp'] + weather_variables]
    concat_list.append(temp)
weather = pd.concat(concat_list)
weather['datetime'] = pd.to_datetime(weather['timestamp'], format='ISO8601', utc=True) + pd.Timedelta(hours=-1)
weather = weather\
    .drop(columns='timestamp')\
    .groupby('datetime', as_index=False)\
    .agg('mean')
print(weather.shape)
weather.head()

### Day-Ahead Price Data

In [ ]:
%%time

url = 'https://api.energy-charts.info/price'
parameters = {
    'start':'2018-12-31T12:00:00Z',
    'end':'2024-12-31T23:00:00Z'
}
data = requests.get(url, params=parameters).json()
data.pop('license_info'); data.pop('unit'); data.pop('deprecated')
price = pd.DataFrame(data)
price['datetime'] = pd.to_datetime(price['unix_seconds'], unit='s', utc=True)
price = price.drop(columns='unix_seconds')
print(price.shape)
price.head()

(52620, 2)
CPU times: user 119 ms, sys: 25.5 ms, total: 145 ms
Wall time: 7.58 s

   price                  datetime
0  63.91 2018-12-31 12:00:00+00:00
1  59.68 2018-12-31 13:00:00+00:00
2  56.60 2018-12-31 14:00:00+00:00
3  63.28 2018-12-31 15:00:00+00:00
4  68.01 2018-12-31 16:00:00+00:00

### Production Data

In [ ]:
%%time

url = 'https://api.energy-charts.info/public_power'
parameters = {
    'start':'2018-12-31T12:00:00Z',
    'end':'2025-01-01T00:00:00Z'
}
data = requests.get(url, params=parameters).json()
public_power = pd.DataFrame()
public_power['datetime'] = pd.to_datetime(data['unix_seconds'], unit='s', utc=True) + pd.Timedelta(hours=-1)
for production_type_data in data['production_types']:
    col = production_type_data['name'].lower().replace(' ', '_').replace('-', '_')
    public_power[col] = production_type_data['data']
public_power = public_power[
    public_power['datetime'].dt.minute == 0
].drop(columns=['hydro_pumped_storage_consumption', 'cross_border_electricity_trading'])
print(public_power.shape)
public_power.head()

(52621, 21)
CPU times: user 1.49 s, sys: 66.5 ms, total: 1.56 s
Wall time: 14.5 s

,datetime,nuclear,hydro_run_of_river,biomass,fossil_brown_coal_/_lignite,fossil_hard_coal,fossil_oil,fossil_coal_derived_gas,fossil_gas,geothermal,hydro_water_reservoir,hydro_pumped_storage,others,waste,wind_offshore,wind_onshore,solar,load,residual_load,renewable_share_of_load,renewable_share_of_generation
0,2018-12-31 11:00:00+00:00,9404.7,1636.4,4976.9,11187.2,6217.0,466.1,433.5,4463.1,15.4,78.1,1217.8,491.3,1352.1,2402.4,3624.6,2239.2,53415.6,45149.4,29.2,31.0
4,2018-12-31 12:00:00+00:00,9364.0,1643.9,4958.3,11197.6,6028.8,466.5,431.8,4509.2,15.4,109.7,1449.1,491.4,1432.4,3134.9,3995.0,1631.0,52750.6,43989.7,30.6,31.7
8,2018-12-31 13:00:00+00:00,9362.5,1647.2,4941.6,11152.7,6032.8,469.3,410.7,4473.6,15.4,103.0,1426.6,491.5,1433.8,3534.7,4902.5,664.7,51944.2,42842.3,31.7,32.2
12,2018-12-31 14:00:00+00:00,9281.1,1687.3,4993.3,11127.4,6038.5,468.7,413.7,4477.3,15.2,73.7,2078.1,488.2,1419.6,4032.4,6035.3,69.9,53075.2,42937.5,33.1,33.3
16,2018-12-31 15:00:00+00:00,9277.2,1686.6,4997.7,11158.7,6001.9,468.7,502.5,4708.9,15.2,66.0,3101.4,488.5,1430.7,4014.4,7800.3,0.8,56323.7,44508.2,34.1,34.5

### Cross-Border Electricity Trading Data

In [ ]:
%%time

url = 'https://api.energy-charts.info/cbet'
parameters = {
    'start':'2018-12-31T12:00:00Z',
    'end':'2025-01-01T00:00:00Z'
}
data = requests.get(url, parameters).json()
cbet = pd.DataFrame()
cbet['datetime'] = pd.to_datetime(data['unix_seconds'], unit='s', utc=True) + pd.Timedelta(hours=-1)
for country_data in data['countries']:
    col = country_data['name'].lower().replace(' ', '_').replace('-', '_') + '_cbet'
    cbet[col] = country_data['data']
cbet = cbet[
    cbet['datetime'].dt.minute == 0
]
print(cbet.shape)
cbet.head()

(52621, 13)
CPU times: user 985 ms, sys: 52.1 ms, total: 1.04 s
Wall time: 7.85 s

,datetime,austria_cbet,belgium_cbet,czech_republic_cbet,denmark_cbet,france_cbet,luxembourg_cbet,netherlands_cbet,norway_cbet,poland_cbet,sweden_cbet,switzerland_cbet,sum_cbet
0,2018-12-31 11:00:00+00:00,0.188,NaN,2.189,1.885,-0.528,-0.457,-2.654,NaN,0.655,0.000,-0.435,0.843
4,2018-12-31 12:00:00+00:00,-0.994,NaN,1.608,1.885,-0.339,-0.449,-2.547,NaN,0.590,0.364,-0.724,-0.605
8,2018-12-31 13:00:00+00:00,-1.338,NaN,1.118,1.845,-0.519,-0.442,-2.467,NaN,0.530,0.000,-0.673,-1.946
12,2018-12-31 14:00:00+00:00,-1.872,NaN,1.375,1.685,-0.362,-0.444,-1.836,NaN,0.783,0.000,-0.346,-1.017
16,2018-12-31 15:00:00+00:00,-0.967,NaN,1.548,1.455,-1.118,-0.466,-2.730,NaN,0.911,0.000,-0.597,-1.964

----

## Data Concatenation

In [ ]:
df = reduce(
    lambda l, r : l.merge(r, on='datetime', how='outer'),
    [weather, price, public_power, cbet]
).sort_values(by='datetime', ascending=True)
df.to_csv('../data/raw/dataset.csv', index=False)
print(df.shape)
df.head()

(52621, 39)

,datetime,precipitation,cloud_cover,sunshine,temperature,relative_humidity,price,nuclear,hydro_run_of_river,biomass,fossil_brown_coal_/_lignite,fossil_hard_coal,fossil_oil,fossil_coal_derived_gas,fossil_gas,geothermal,hydro_water_reservoir,hydro_pumped_storage,others,waste,wind_offshore,wind_onshore,solar,load,residual_load,renewable_share_of_load,renewable_share_of_generation,austria_cbet,belgium_cbet,czech_republic_cbet,denmark_cbet,france_cbet,luxembourg_cbet,netherlands_cbet,norway_cbet,poland_cbet,sweden_cbet,switzerland_cbet,sum_cbet
0,2018-12-31 11:00:00+00:00,0.400,93.50,2.00,6.875,92.75,NaN,9404.7,1636.4,4976.9,11187.2,6217.0,466.1,433.5,4463.1,15.4,78.1,1217.8,491.3,1352.1,2402.4,3624.6,2239.2,53415.6,45149.4,29.2,31.0,0.188,NaN,2.189,1.885,-0.528,-0.457,-2.654,NaN,0.655,0.000,-0.435,0.843
1,2018-12-31 12:00:00+00:00,0.250,96.75,0.75,7.050,92.50,63.91,9364.0,1643.9,4958.3,11197.6,6028.8,466.5,431.8,4509.2,15.4,109.7,1449.1,491.4,1432.4,3134.9,3995.0,1631.0,52750.6,43989.7,30.6,31.7,-0.994,NaN,1.608,1.885,-0.339,-0.449,-2.547,NaN,0.590,0.364,-0.724,-0.605
2,2018-12-31 13:00:00+00:00,0.100,100.00,0.00,7.250,91.25,59.68,9362.5,1647.2,4941.6,11152.7,6032.8,469.3,410.7,4473.6,15.4,103.0,1426.6,491.5,1433.8,3534.7,4902.5,664.7,51944.2,42842.3,31.7,32.2,-1.338,NaN,1.118,1.845,-0.519,-0.442,-2.467,NaN,0.530,0.000,-0.673,-1.946
3,2018-12-31 14:00:00+00:00,0.075,100.00,0.00,7.250,92.25,56.60,9281.1,1687.3,4993.3,11127.4,6038.5,468.7,413.7,4477.3,15.2,73.7,2078.1,488.2,1419.6,4032.4,6035.3,69.9,53075.2,42937.5,33.1,33.3,-1.872,NaN,1.375,1.685,-0.362,-0.444,-1.836,NaN,0.783,0.000,-0.346,-1.017
4,2018-12-31 15:00:00+00:00,0.050,96.75,0.00,7.050,94.00,63.28,9277.2,1686.6,4997.7,11158.7,6001.9,468.7,502.5,4708.9,15.2,66.0,3101.4,488.5,1430.7,4014.4,7800.3,0.8,56323.7,44508.2,34.1,34.5,-0.967,NaN,1.548,1.455,-1.118,-0.466,-2.730,NaN,0.911,0.000,-0.597,-1.964

In [ ]:
print(df.dtypes)
print(f'Total NaNs: {df.isna().sum().sum()}\n')
print(df.isna().sum())

datetime                         datetime64[ns, UTC]
precipitation                                float64
cloud_cover                                  float64
sunshine                                     float64
temperature                                  float64
relative_humidity                            float64
price                                        float64
nuclear                                      float64
hydro_run_of_river                           float64
biomass                                      float64
fossil_brown_coal_/_lignite                  float64
fossil_hard_coal                             float64
fossil_oil                                   float64
fossil_coal_derived_gas                      float64
fossil_gas                                   float64
geothermal                                   float64
hydro_water_reservoir                        float64
hydro_pumped_storage                         float64
others                                       float64
waste                                        float64
wind_offshore                                float64
wind_onshore                                 float64
solar                                        float64
load                                         float64
residual_load                                float64
renewable_share_of_load                      float64
renewable_share_of_generation                float64
austria_cbet                                 float64
belgium_cbet                                 float64
czech_republic_cbet                          float64
denmark_cbet                                 float64
france_cbet                                  float64
luxembourg_cbet                              float64
netherlands_cbet                             float64
norway_cbet                                  float64
poland_cbet                                  float64
sweden_cbet                                  float64
switzerland_cbet                             float64
sum_cbet                                     float64
dtype: object
Total NaNs: 86171

datetime                             0
precipitation                        0
cloud_cover                          0
sunshine                         10593
temperature                          0
relative_humidity                    0
price                                1
nuclear                          15027
hydro_run_of_river                   0
biomass                              0
fossil_brown_coal_/_lignite          0
fossil_hard_coal                     0
fossil_oil                           0
fossil_coal_derived_gas          29833
fossil_gas                           0
geothermal                           0
hydro_water_reservoir                0
hydro_pumped_storage                 0
others                               0
waste                                0
wind_offshore                        0
wind_onshore                         0
solar                                0
load                                 0
residual_load                        0
renewable_share_of_load              0
renewable_share_of_generation        0
austria_cbet                         0
belgium_cbet                     16091
czech_republic_cbet                  0
denmark_cbet                         0
france_cbet                          0
luxembourg_cbet                      0
netherlands_cbet                     0
norway_cbet                      14626
poland_cbet                          0
sweden_cbet                          0
switzerland_cbet                     0
sum_cbet                             0
dtype: int64

----

## Train-Test Split

In [2]:
df = pd.read_csv('../data/raw/dataset.csv')
df['datetime'] = pd.to_datetime(df['datetime'], utc=True)
df = df.set_index('datetime')

In [4]:
## selecting features based on domain knowledge
subset = [
    'price',
    'precipitation', 'temperature', 'relative_humidity',
    'load', 'renewable_share_of_load', 'renewable_share_of_generation',
    'sum_cbet'
]
df_subset = df[subset]

## lagging features to abide by the "day-ahead" constraint
for col in subset[1:]:
    df_subset.loc[:, col] = df_subset[col].shift(12)

## 2019 - 2023 is train_val : 2024 is test
## saving train and test splits (unstandardized, standardized, scalers)
save_splits(
    df=df_subset,
    time_splits=[
        (   # train_start            # train_end
            '2019-01-01 00:00:00+00:00', '2022-12-31 23:00:00+00:00',
            '2023-01-01 00:00:00+00:00', '2023-12-31 23:00:00+00:00'
        )   # val_start                 # val_end
    ],
    f_names=[
        ('df_train', 'df_val')
    ]
)
save_splits(
    df=df_subset,
    time_splits=[
        (   # train_val_start            # train_val_end
            '2019-01-01 00:00:00+00:00', '2023-12-31 23:00:00+00:00',
            '2024-01-01 00:00:00+00:00', '2024-12-31 23:00:00+00:00'
        )   # test_start                 # test_end
    ],
    f_names=[
        ('df_train_val', 'df_test')
    ]
)
save_splits(
    df=df_subset,
    time_splits=[
        (   # train_start            # train_end
            '2019-01-01 00:00:00+00:00', '2022-12-31 23:00:00+00:00',
            '2024-01-01 00:00:00+00:00', '2024-12-31 23:00:00+00:00'
        )   # test_start                 # test_end
    ],
    f_names=[
        ('df_train', 'df_test')
    ]
)

## saving train and val splits (unstandardized, standardized, scalers)
save_splits(
    df=df_subset,
    time_splits=[
        # split 1
        (   # train_start                # train_end
            '2019-01-01 00:00:00+00:00', '2022-12-31 23:00:00+00:00',
            '2023-01-01 00:00:00+00:00', '2023-06-30 23:00:00+00:00'
        ),  # val_start                  # val_end
        # split 2
        (   # train_start                # train_end
            '2019-01-01 00:00:00+00:00', '2023-06-30 23:00:00+00:00',
            '2023-07-01 00:00:00+00:00', '2023-12-31 23:00:00+00:00'
        ),  # val_start                  # val_end
    ],
    f_names=[
        ('df_train1', 'df_val1'),   # split 1
        ('df_train2', 'df_val2')    # split 2
    ]
)

----

## Data Dictionary

In [ ]:
descriptions_units = {
    'datetime':                         ('ISO 8601-formatted timestamp of this record in UTC.', 'YYYY-MM-DDThh:mm:ss'),
    'precipitation':                    ('Total precipitation during the following hour.', 'mm'),
    'cloud_cover':                      ('Total cloud cover an hour after the timestamp.', '%'),
    'sunshine':                         ('Sunshine duration during the following hour.', 'min'),
    'temperature':                      ('Air temperature an hour after the timestamp, 2 m above the ground.', 'ºC'),
    'relative_humidity':                ('Relative humidity an hour after the timestamp.', '%'),
    'price':                            ('The day-ahead spot market price for the DE-LU bidding zone. Takes the last 15-minute interval value and assigns to the start of the hour interval.', 'EUR/MWh'),
    'hydro_run_of_river':               ('Electricity generation from hydro run-of-river recorded at the end of the following hour.', 'MW'),
    'biomass':                          ('Electricity generation from biomass recorded at the end of the following hour.', 'MW'),
    'fossil_brown_coal_/_lignite':      ('Electricity generation from fossil brown coal / lignite recorded at the end of the following hour.', 'MW'),
    'fossil_hard_coal':                 ('Electricity generation from fossil hard coal recorded at the end of the following hour.', 'MW'),
    'fossil_oil':                       ('Electricity generation from fossil oil recorded at the end of the following hour.', 'MW'),
    'fossil_coal_derived_gas':          ('Electricity generation from fossil coal-derived gas recorded at the end of the following hour.', 'MW'),
    'fossil_gas':                       ('Electricity generation from fossil gas recorded at the end of the following hour.', 'MW'),
    'geothermal':                       ('Electricity generation from geothermal recorded at the end of the following hour.', 'MW'),
    'hydro_water_reservoir':            ('Electricity generation from hydro water reservoir recorded at the end of the following hour.', 'MW'),
    'hydro_pumped_storage':             ('Electricity generation from pumped storage recorded at the end of the following hour.', 'MW'),
    'others':                           ('Electricity generation from other sources recorded at the end of the following hour.', 'MW'),
    'waste':                            ('Electricity generation from waste recorded at the end of the following hour.', 'MW'),
    'wind_offshore':                    ('Electricity generation from wind offshore recorded at the end of the following hour.', 'MW'),
    'wind_onshore':                     ('Electricity generation from wind onshore recorded at the end of the following hour.', 'MW'),
    'solar':                            ('Electricity generation from solar recorded at the end of the following hour.', 'MW'),
    'load':                             ('Instantaneous grid load recorded at the end of the following hour.', 'MW'),
    'residual_load':                    ('Instantaneous grid load not covered by renewable generation sources recorded at the end of the following hour.', 'MW'),
    'renewable_share_of_load':          ('Instantaneous grid load covered by renewable generation sources recorded at the end of the following hour.', 'MW'),
    'renewable_share_of_generation':    ('Total electricity generation from renewable generation sources recorded at the end of the following hour.', 'MW'),
    'austria_cbet':                     ('The cross-border electricity trading with Austria recorded at the end of the following hour. Positive values indicate an import of electricity, whereas negative values show electricity exports.', 'GW'),
    'belgium_cbet':                     ('The cross-border electricity trading with Belgium recorded at the end of the following hour. Positive values indicate an import of electricity, whereas negative values show electricity exports.', 'GW'),
    'czech_republic_cbet':              ('The cross-border electricity trading with Czech Republic recorded at the end of the following hour. Positive values indicate an import of electricity, whereas negative values show electricity exports.', 'GW'),
    'denmark_cbet':                     ('The cross-border electricity trading with Denmark recorded at the end of the following hour. Positive values indicate an import of electricity, whereas negative values show electricity exports.', 'GW'),
    'france_cbet':                      ('The cross-border electricity trading with France recorded at the end of the following hour. Positive values indicate an import of electricity, whereas negative values show electricity exports.', 'GW'),
    'luxembourg_cbet':                  ('The cross-border electricity trading with Luxembourg recorded at the end of the following hour. Positive values indicate an import of electricity, whereas negative values show electricity exports.', 'GW'),
    'netherlands_cbet':                 ('The cross-border electricity trading with Netherlands recorded at the end of the following hour. Positive values indicate an import of electricity, whereas negative values show electricity exports.', 'GW'),
    'norway_cbet':                      ('The cross-border electricity trading with Norway recorded at the end of the following hour. Positive values indicate an import of electricity, whereas negative values show electricity exports.', 'GW'),
    'poland_cbet':                      ('The cross-border electricity trading with Poland recorded at the end of the following hour. Positive values indicate an import of electricity, whereas negative values show electricity exports.', 'GW'),
    'sweden_cbet':                      ('The cross-border electricity trading with Sweden recorded at the end of the following hour. Positive values indicate an import of electricity, whereas negative values show electricity exports.', 'GW'),
    'switzerland_cbet':                 ('The cross-border electricity trading with Switzerland recorded at the end of the following hour. Positive values indicate an import of electricity, whereas negative values show electricity exports.', 'GW'),
    'sum_cbet':                         ('The cross-border electricity trading with all other countries recorded at the end of the following hour. Positive values indicate an import of electricity, whereas negative values show electricity exports.', 'GW')
}

data_dict = {}
for var in df.columns:
    data_dict[var] = [df[var].dtype, descriptions_units[var][1], descriptions_units[var][0]]

data_dict_df = pd.DataFrame.from_dict(
    data_dict,
    orient='index',
    columns=['dtype', 'units', 'description']
)
data_dict_df.to_csv('data_dictionary.csv')
print(data_dict_df.shape)
data_dict_df.head(100)